encoding: UTF-8
# Site
title:              Study & Store
bio:                "Let's learn"
description:        "tinygun's blog"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/avatar.jpg'
background:         'assets/img/triangle_2.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             ko_KR
baseurl:		""
url:                https://tinygun.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   tinygun

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:	tinygun77@gmail.com
github-url:         tinygun
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#youtube:           username
youtube-channel:   UCmnZSiv7bCJ2yCu4S_Tmvlg?view_as=subscriber

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

category_archive:
  type: liquid
  path: /categories/